using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MainSceneController : SceneController {

	public void onStartVehicleConfigurator()
    {
        UnityEngine.SceneManagement.SceneManager.LoadScene("02 - configurator");
    }

    public void onStartRoomDesigner()
    {
        this.GetComponent<SceneManager>().requestSceneChange("03 - room-designer");
    }

    public void onStartDemoScene()
    {
        this.GetComponent<SceneManager>().requestSceneChange("04 - demo");
    }
}
